#!/bin/bash 
#SBATCH -J profile_8
#SBATCH --nodes=1
#SBATCH --tasks=8
#SBATCH --partition=devel
#SBATCH -o profile_8.out 
#SBATCH -e profile_8.err 
#SBATCH --ntasks-per-node=8
#SBATCH --time=00:10:00

module load intel-para/2015.07
module load Score-P/1.4.2
module load Boost/1.58.0-Python-2.7.10

export SCOREP_ENABLE_PROFILING=1
export SCOREP_ENABLE_TRACING=0
export SCOREP_EXPERIMENT_DIRECTORY=profile_8
export SCOREP_TOTAL_MEMORY=128M
export SCOREP_PROFILING_MAX_CALLPATH_DEPTH=55
srun mpi_pfasst --dt 0.01 --tend 0.16 --num_iters 20 --abs_res_tol 1e-10 --nocolor
